name: Makefile CI

on:
  push: {}
  pull_request:
    branches: [ $default-branch ]

jobs:

  build-and-test:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3

    - name: Install swift wkhtmltopdf
      run: brew install swift wkhtmltopdf

    - name: Set Up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.x

    - name: Check Versions
      run: swift --version && xcodebuild -version && go version && make --version && wkhtmltopdf --version && xcode-select --print-path

    - name: List libraries
      run: ls -l `xcode-select --print-path`/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift

    - name: Build
      run: make

    - name: Test
      run: make test

    - name: Upload Code Coverage
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
