name: Makefile CI

on:
  push: {}
  pull_request:
    branches: [ $default-branch ]

jobs:

  build-and-test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install wkhtmltopdf
      run: brew install wkhtmltopdf

    - name: Set Up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.x

    - name: Check versions
      run: swift --version && xcodebuild -version && go version && make --version && wkhtmltopdf --version

    - name: Build
      run: make

    - name: Test
      run: make test

    - name: Upload Code Coverage
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
