name: Makefile CI

on:
  push: {}
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:

jobs:

  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'macos-13', 'macos-12' ]
    steps:
    - uses: actions/checkout@v3

    - name: Install  wkhtmltopdf
      run: brew install wkhtmltopdf

#    - name: Set Up Go
#      uses: actions/setup-go@v3
#      with:
#        go-version: 1.x

    - name: Install  golang
      run: brew install golang

    - name: List Libraries
      run: ls -l `xcode-select --print-path`/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift

    - name: List Frameworks
      run: ls -l /Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks

    - name: Build
      run: make

    - name: Test
      run: make test

    - name: Upload Code Coverage
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
